from elasticsearch import Elasticsearch as es

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "w5bmIU+Z1a4fUNh8V3tS"

# Create the client instance
client = es(
    "https://localhost:9200",
    ca_certs="certs/ca_1650694705031.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)


def search_countries_with_name(search_term: str):
    # query = {"match": {"name": search_term}}
    query = {"regexp": { "name": f'.*{search_term}.*'}}
    resp = client.search(index="countries", query=query)

    all_hits = []
    for hit in resp['hits']['hits']:
        all_hits.append(hit["_source"])
    return all_hits


def search_cities_with_name(search_term: str):
    query = {"regexp": { "name": f'.*{search_term}.*'}}
    resp = client.search(index="cities", query=query)

    all_hits = []
    for hit in resp['hits']['hits']:
        all_hits.append(hit["_source"])
    return all_hits

